# Generated by precisionFDA exporter (v1.0.3) on 2018-06-14 04:21:47 +0000
# The asset download links in this file are valid only for 24h.

# Exported app: gatk4-haplotypecallerspark-hs37d5, revision: 2, authored by: george.asimenos
# https://precision.fda.gov/apps/app-F9yPbZ00py9VPV0V5g8662v8

# For more information please consult the app export section in the precisionFDA docs

# Start with Ubuntu 14.04 base image
FROM ubuntu:14.04

# Install default precisionFDA Ubuntu packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
	aria2 \
	byobu \
	cmake \
	cpanminus \
	curl \
	dstat \
	g++ \
	git \
	htop \
	libboost-all-dev \
	libcurl4-openssl-dev \
	libncurses5-dev \
	make \
	perl \
	pypy \
	python-dev \
	python-pip \
	r-base \
	ruby1.9.3 \
	wget \
	xz-utils

# Install default precisionFDA python packages
RUN pip install \
	requests==2.5.0 \
	futures==2.2.0 \
	setuptools==10.2

# Add DNAnexus repo to apt-get
RUN /bin/bash -c "echo 'deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/amd64/' > /etc/apt/sources.list.d/dnanexus.list"
RUN /bin/bash -c "echo 'deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/all/' >> /etc/apt/sources.list.d/dnanexus.list"
RUN curl https://wiki.dnanexus.com/images/files/ubuntu-signing-key.gpg | apt-key add -

# Install app-specific Ubuntu packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
	openjdk-8-jre-headless

# Download app assets
RUN curl https://dl.dnanex.us/F/D/0j3pPqp3F4pF2fjKfYYB9kQzfX142KjzfK36QYGJ/hs37d5-2bit.tar.gz | tar xzf - -C / --no-same-owner --no-same-permissions
RUN curl https://dl.dnanex.us/F/D/Vv6F70042zBGpkxj14kQ0K4Fk1gyqgj8pFqZ5BP3/htslib-1.3.tar.gz | tar xzf - -C / --no-same-owner --no-same-permissions
RUN curl https://dl.dnanex.us/F/D/8V5X65qQKvp98Q7p77xFFq7X06GXFJKzbx8BppxP/gatk-4.0.1.1.tar | tar xf - -C / --no-same-owner --no-same-permissions

# Download helper executables
RUN curl https://dl.dnanex.us/F/D/0K8P4zZvjq9vQ6qV0b6QqY1z2zvfZ0QKQP4gjBXp/emit-1.0.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions
RUN curl https://dl.dnanex.us/F/D/bByKQvv1F7BFP3xXPgYXZPZjkXj9V684VPz8gb7p/run-1.2.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions

# Write app spec and code to root folder
RUN ["/bin/bash","-c","echo -E \\{\\\"spec\\\":\\{\\\"input_spec\\\":\\[\\{\\\"name\\\":\\\"mappings\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Mappings\\ BAM\\\",\\\"help\\\":\\\"A\\ sorted\\ BAM\\ file\\ on\\ which\\ variants\\ will\\ be\\ called\\\"\\},\\{\\\"name\\\":\\\"extra_opts\\\",\\\"class\\\":\\\"string\\\",\\\"optional\\\":true,\\\"label\\\":\\\"Extra\\ command-line\\ options\\\",\\\"help\\\":\\\"Additional\\ command-line\\ options\\ that\\ will\\ be\\ appended\\ to\\ the\\ command\\ line\\\"\\}\\],\\\"output_spec\\\":\\[\\{\\\"name\\\":\\\"variants\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"Variants\\ VCF\\\",\\\"help\\\":\\\"The\\ generated\\ variants\\ \\(in\\ bgzipped\\ VCF\\ format\\)\\\"\\}\\],\\\"internet_access\\\":false,\\\"instance_type\\\":\\\"himem-16\\\"\\},\\\"assets\\\":\\[\\\"file-F5Y8y4j0qVb9fyBX16y3KF94\\\",\\\"file-BpBq6GQ0qVb40z0FGk4ZYjkY\\\",\\\"file-F9yPZFj0qVbJfbz10bX1fzzF\\\"\\],\\\"packages\\\":\\[\\\"openjdk-8-jre-headless\\\"\\]\\} \u003e /spec.json"]
RUN ["/bin/bash","-c","echo -E \\{\\\"code\\\":\\\"gatk\\ HaplotypeCallerSpark\\ -I\\ \\\\\\\"\\$mappings_path\\\\\\\"\\ -R\\ hs37d5.2bit\\ -O\\ \\\\\\\"\\$mappings_prefix\\\\\\\".vcf\\ \\$extra_opts\\\\n\\\\nbgzip\\ \\\\\\\"\\$mappings_prefix\\\\\\\".vcf\\\\nemit\\ variants\\ \\\\\\\"\\$mappings_prefix\\\\\\\".vcf.gz\\\"\\} | python -c 'import sys,json; print json.load(sys.stdin)[\"code\"]' \u003e /script.sh"]

# Create directory /work and set it to $HOME and CWD
RUN mkdir -p /work
ENV HOME="/work"
WORKDIR /work

# Set entry point to container
ENTRYPOINT ["/usr/bin/run"]

VOLUME /data
VOLUME /work